// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdlmvizqxtqtzoyxlgif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbG12aXpxeHRxdHpveXhsZ2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODY0OTcsImV4cCI6MjA2ODg2MjQ5N30.8ym1fhI0tWncBHlZUc_vtscUz6vlMPuyrwkVeLDaSao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});